/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./schema";
export type PublicProviderSlug = z.infer<
  typeof generated.publicProviderSlugSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicUserStatus = z.infer<typeof generated.publicUserStatusSchema>;
export type PublicUsersInsert = z.infer<
  typeof generated.publicUsersInsertSchema
>;
export type PublicUsersUpdate = z.infer<
  typeof generated.publicUsersUpdateSchema
>;
export type PublicNonUpdatableViewRow = z.infer<
  typeof generated.publicNonUpdatableViewRowSchema
>;
export type PublicGetStatusArgs = z.infer<
  typeof generated.publicGetStatusArgsSchema
>;
export type PublicGetStatusReturns = z.infer<
  typeof generated.publicGetStatusReturnsSchema
>;
export type SchemaBUserStatus = z.infer<
  typeof generated.schemaBUserStatusSchema
>;
export type SchemaBUsersRow = z.infer<typeof generated.schemaBUsersRowSchema>;
export type SchemaBUsersInsert = z.infer<
  typeof generated.schemaBUsersInsertSchema
>;
export type SchemaBUsersUpdate = z.infer<
  typeof generated.schemaBUsersUpdateSchema
>;
export type SchemaBNonUpdatableViewRow = z.infer<
  typeof generated.schemaBNonUpdatableViewRowSchema
>;
export type SchemaBGetDeploymentConfigSchemaArgs = z.infer<
  typeof generated.schemaBGetDeploymentConfigSchemaArgsSchema
>;
export type SchemaBGetDeploymentConfigSchemaReturns = z.infer<
  typeof generated.schemaBGetDeploymentConfigSchemaReturnsSchema
>;
export type SchemaBGetStatusArgs = z.infer<
  typeof generated.schemaBGetStatusArgsSchema
>;
export type SchemaBGetStatusReturns = z.infer<
  typeof generated.schemaBGetStatusReturnsSchema
>;
export type PublicUsersRow = z.infer<typeof generated.publicUsersRowSchema>;
