// Generated by ts-to-zod
import { z } from "zod";

import * as generated from "./schema";

export type Json = z.infer<typeof generated.jsonSchema>;

export type publicUserStatusSchema = z.infer<
  typeof generated.publicUserStatusSchemaSchema
>;

export type publicUsersInsertSchema = z.infer<
  typeof generated.publicUsersInsertSchemaSchema
>;

export type publicUsersUpdateSchema = z.infer<
  typeof generated.publicUsersUpdateSchemaSchema
>;

export type publicNonUpdatableViewRowSchema = z.infer<
  typeof generated.publicNonUpdatableViewRowSchemaSchema
>;

export type publicGetStatusArgsSchema = z.infer<
  typeof generated.publicGetStatusArgsSchemaSchema
>;

export type publicGetStatusReturnsSchema = z.infer<
  typeof generated.publicGetStatusReturnsSchemaSchema
>;

export type schema_b_userStatus = z.infer<
  typeof generated.schemaBUserStatusSchema
>;

export type public_userStatus = z.infer<
  typeof generated.publicUserStatusSchema
>;

export type schemaBUsersRowSchema = z.infer<
  typeof generated.schemaBUsersRowSchemaSchema
>;

export type schemaBUserStatusSchema = z.infer<
  typeof generated.schemaBUserStatusSchemaSchema
>;

export type schemaBUsersUpdateSchema = z.infer<
  typeof generated.schemaBUsersUpdateSchemaSchema
>;

export type schemaBNonUpdatableViewRowSchema = z.infer<
  typeof generated.schemaBNonUpdatableViewRowSchemaSchema
>;

export type schemaBGetDeploymentConfigSchemaArgsSchema = z.infer<
  typeof generated.schemaBGetDeploymentConfigSchemaArgsSchemaSchema
>;

export type schemaBGetDeploymentConfigSchemaReturnsSchema = z.infer<
  typeof generated.schemaBGetDeploymentConfigSchemaReturnsSchemaSchema
>;

export type schemaBGetStatusArgsSchema = z.infer<
  typeof generated.schemaBGetStatusArgsSchemaSchema
>;

export type schemaBGetStatusReturnsSchema = z.infer<
  typeof generated.schemaBGetStatusReturnsSchemaSchema
>;

export type publicUsersRowSchema = z.infer<
  typeof generated.publicUsersRowSchemaSchema
>;

export type schemaBUsersInsertSchema = z.infer<
  typeof generated.schemaBUsersInsertSchemaSchema
>;
