// Generated by ts-to-zod
import { z } from "zod";
import * as generated from "./schema";
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicUserStatusSchema = z.infer<
  typeof generated.publicUserStatusSchemaSchema
>;
export type PublicUsersInsertSchema = z.infer<
  typeof generated.publicUsersInsertSchemaSchema
>;
export type PublicUsersUpdateSchema = z.infer<
  typeof generated.publicUsersUpdateSchemaSchema
>;
export type PublicNonUpdatableViewRowSchema = z.infer<
  typeof generated.publicNonUpdatableViewRowSchemaSchema
>;
export type PublicGetStatusArgsSchema = z.infer<
  typeof generated.publicGetStatusArgsSchemaSchema
>;
export type PublicGetStatusReturnsSchema = z.infer<
  typeof generated.publicGetStatusReturnsSchemaSchema
>;
export type SchemaBUserstatus = z.infer<
  typeof generated.schemaBUserStatusSchema
>;
export type PublicUserstatus = z.infer<typeof generated.publicUserStatusSchema>;
export type SchemaBUsersRowSchema = z.infer<
  typeof generated.schemaBUsersRowSchemaSchema
>;
export type SchemaBUserStatusSchema = z.infer<
  typeof generated.schemaBUserStatusSchemaSchema
>;
export type SchemaBUsersUpdateSchema = z.infer<
  typeof generated.schemaBUsersUpdateSchemaSchema
>;
export type SchemaBNonUpdatableViewRowSchema = z.infer<
  typeof generated.schemaBNonUpdatableViewRowSchemaSchema
>;
export type SchemaBGetDeploymentConfigSchemaArgsSchema = z.infer<
  typeof generated.schemaBGetDeploymentConfigSchemaArgsSchemaSchema
>;
export type SchemaBGetDeploymentConfigSchemaReturnsSchema = z.infer<
  typeof generated.schemaBGetDeploymentConfigSchemaReturnsSchemaSchema
>;
export type SchemaBGetStatusArgsSchema = z.infer<
  typeof generated.schemaBGetStatusArgsSchemaSchema
>;
export type SchemaBGetStatusReturnsSchema = z.infer<
  typeof generated.schemaBGetStatusReturnsSchemaSchema
>;
export type PublicUsersRowSchema = z.infer<
  typeof generated.publicUsersRowSchemaSchema
>;
export type SchemaBUsersInsertSchema = z.infer<
  typeof generated.schemaBUsersInsertSchemaSchema
>;
