/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";

export const jsonSchema = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), jsonSchema),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicPostStatusSchema = z.union([
  z.literal("draft"),
  z.literal("published"),
  z.literal("archived"),
]);

export const publicPostsInsertSchema = z.object({
  id: z.number().optional(),
  title: z.string(),
  content: z.string().optional().nullable(),
  author_id: z.string(),
  status: publicPostStatusSchema.optional(),
  created_at: z.string().optional(),
});

export const publicPostsUpdateSchema = z.object({
  id: z.number().optional(),
  title: z.string().optional(),
  content: z.string().optional().nullable(),
  author_id: z.string().optional(),
  status: publicPostStatusSchema.optional(),
  created_at: z.string().optional(),
});

export const publicPostsRowSchema = z.object({
  id: z.number(),
  title: z.string(),
  content: z.string().nullable(),
  author_id: z.string(),
  status: publicPostStatusSchema,
  created_at: z.string(),
});

export type Json = z.infer<typeof jsonSchema>;
export type PublicPostStatus = z.infer<typeof publicPostStatusSchema>;
export type PublicPostsInsert = z.infer<typeof publicPostsInsertSchema>;
export type PublicPostsUpdate = z.infer<typeof publicPostsUpdateSchema>;
export type PublicPostsRow = z.infer<typeof publicPostsRowSchema>;
