/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), jsonSchema),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicUsersRowSchema = z.object({
  id: z.string(),
  email: z.string(),
  metadata: jsonSchema.nullable(),
});

export const publicUsersInsertSchema = z.object({
  id: z.string().optional(),
  email: z.string(),
  metadata: jsonSchema.optional().nullable(),
});

export const publicUsersUpdateSchema = z.object({
  id: z.string().optional(),
  email: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
});

export const publicUserRoleSchema = z.union([
  z.literal("admin"),
  z.literal("user"),
]);
