/**
 * Example: Using MergeDeep to extend Supabase generated types
 *
 * This demonstrates how supazod supports the MergeDeep pattern from type-fest,
 * which allows users to override JSON field types in Supabase generated types.
 *
 * Note: This file requires `type-fest` package to be installed in your project.
 */
import type { MergeDeep } from 'type-fest';

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

// Original types generated by Supabase CLI
type DatabaseGenerated = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          metadata: Json | null;
        };
        Insert: {
          id?: string;
          email: string;
          metadata?: Json | null;
        };
        Update: {
          id?: string;
          email?: string;
          metadata?: Json | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: 'admin' | 'user';
    };
    CompositeTypes: Record<string, never>;
  };
};

// Custom type to replace the generic Json type
type UserMetadata = {
  avatar: string;
  theme: 'light' | 'dark';
};

// Extended Database type using MergeDeep
export type Database = MergeDeep<
  DatabaseGenerated,
  {
    public: {
      Tables: {
        users: {
          Row: {
            metadata: UserMetadata | null;
          };
          Insert: {
            metadata?: UserMetadata | null;
          };
          Update: {
            metadata?: UserMetadata | null;
          };
        };
      };
    };
  }
>;
